### PR TITLE
Be more faithful to advent.for, namely:

### PR DESCRIPTION
**Pull request by qpliu**
```
	DO 20200 I=1,CLSSES
	IF(CVAL(I).GE.SCORE)GOTO 20210
20200	CONTINUE
	TYPE 20202
20202	FORMAT(/' You just went off my scale!!'/)
	GOTO 25000

20210	CALL SPEAK(CTEXT(I))
	IF(I.EQ.CLSSES-1)GOTO 20220
	K=CVAL(I)+1-SCORE
	KK='s.'
	IF(K.EQ.1)KK='. '
	TYPE 20212,K,KK
20212	FORMAT(/' To achieve the next higher rating, you need',I3,
	1	' more point',A2/)
```

### CODE REVIEW

**Comment by Quuxplusone** [comment]
Am I correct that the current code classifies a 35-point score as "novice class adventurer," and that after your patch the same 35-point score would be classified as "rank amateur"?  And the current code classifies a 349-point score as "Adventurer Grandmaster," and after your patch a 349-point score would be "Master Adventurer Class A"?

Am I correct that KNUT0350 ("advent.w") has the same behavior as my current code?  And you contend that WOOD0350 has the same behavior as your patch? If so, you may be owed something from the [Bank of San Seriffe](https://www-cs-faculty.stanford.edu/~knuth/fg.html)!

I *think* that all of the above is right (and that you're right), but I'd like to see a transcript of a 35-point or 349-point game (in each of KNUT0350, ODWY0350, and WOOD0350-if-possible-but-at-least-some-relatively-untouched-Fortran-version) to make sure. I'll get around to that eventually myself, but I'd really appreciate it if someone beats me to it.

**Comment by qpliu** [comment]
This VT100 image from Wikipedia suggests that the FORTRAN version requires 36 points to achieve novice class adventurer.

VT100 image

**Comment by Quuxplusone** [comment]
I see what you mean: 27+9 = 36.
This morning I confirmed that LUPI0440 sets the first break at 42+9 = 51 (not 50), and MCDO0551 sets the first break at 73 (not 72). But KNUT0350 sets the first break at 27+8 = 35, which does seem inconsistent with WOOD0350!
So I am proposing to update the `say_score` routines in ODWY0350, ODWY0440, and ODWY0551.

Contrariwise: PLAT0550 sets the first break at 20 points, and ODWY0550 seems to match PLAT0550's behavior, so that's okay. (Platt's A-code uses a hard-coded nest of `if`s, not a loop over an array of `class_scores` as in the Fortran versions.)

Are you planning to report the bug in Knuth's version, also?  The procedure for reporting bugs is described at the bottom of https://www-cs-faculty.stanford.edu/~knuth/fg.html , and I would be happy to help you draft that email if you want; just email me. :)

**Comment by qpliu** [comment]
Thanks.  I just reported the bug to Knuth.

**Comment by Quuxplusone** [comment]
Merged 531e061bdeeb782229a11c030f0164310a33f9cd. Thanks very much for this bug report!

**Comment by Quuxplusone** [comment]
Belated update: [Errata to the third printing of _Fun & Games_ (2012)](https://www-cs-faculty.stanford.edu/~knuth/fg.html) now contains:

```
*page 382, line -8 (6 October 2018)
change $\le k$ to $<k$
*page 382, line -4 (6 October 2018)
change $[j]-k$ to $[j]+1-k$
*page 382, line -4 (29 April 2019)
change $\equiv k+1$ to $\equiv k$
```

i.e.

```diff
 @<Print the score and say adieu@>=
 k=score();
 printf("You scored %d point%s out of a possible %d, using %d turn%s.\n",
    k,k==1? "": "s",max_score,turns,turns==1? "": "s");
-for (j=0;class_score[j]<=k;j++);
+for (j=0;class_score[j]<k;j++);
 printf("%s\nTo achieve the next higher rating",class_message[j]);
 if (j<highest_class)
-  printf(", you need %d more point%s.\n",class_score[j]-k,
-                 class_score[j]==k+1? "": "s");
+  printf(", you need %d more point%s.\n",class_score[j]+1-k,
+                 class_score[j]==k? "": "s");
 else printf(" would be a neat trick!\nCongratulations!!\n");
```

**Pull request closed without merging**
